### ISSUE TITLE
check-tls-certs and Proxies

### ISSUE THREAD

**Issue by cyd01** [ilri/rmg-check-tls-certs#3]
Hello
Can this tool be used trough a proxy.
I've tried to define "classical variables" (`HTTPS_PROXY, https_proxy ...`) without success.
The process try to request the internal DNS, rather than going to the proxy?

```
export HTTPS_PROXY=my.proxy.com:8080
export https_proxy=${HTTPS_PROXY}
./check-tls-certs -days 3400 -hosts=$(pwd)/check-tls-certs.lst
2020/04/09 09:40:25 worker up!...checking ssl certs
2020/04/09 09:40:25 tld.domain.com:443: dial tcp: lookup tld.domain.com on 192.168.36.29:53: no such host
```

**Comment by alanorth** [comment]
@cyd01 Unfortunately I haven't used this project in five years, so I have no idea! :\
